package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Semantic Financial Colors (Universal)
val IncomeGreen = Color(0xFF10B981) // Vibrant Emerald
val IncomeGreenDark = Color(0xFF059669)
val IncomeGreenContainerLight = Color(0xFFECFDF5)
val IncomeGreenContainerDark = Color(0xFF064E3B)

val ExpenseRed = Color(0xFFEF4444) // Vibrant Rose/Crimson
val ExpenseRedDark = Color(0xFFDC2626)
val ExpenseRedContainerLight = Color(0xFFFEF2F2)
val ExpenseRedContainerDark = Color(0xFF7F1D1D)

// Theme 1: Classic (Slate, Indigo, Steel)
val ClassicPrimaryLight = Color(0xFF1E293B)
val ClassicOnPrimaryLight = Color(0xFFFFFFFF)
val ClassicPrimaryContainerLight = Color(0xFFE2E8F0)
val ClassicSecondaryLight = Color(0xFF3B82F6)
val ClassicTertiaryLight = Color(0xFF0EA5E9)
val ClassicBackgroundLight = Color(0xFFF8FAFC)
val ClassicSurfaceLight = Color(0xFFFFFFFF)
val ClassicSurfaceVariantLight = Color(0xFFF1F5F9)

val ClassicPrimaryDark = Color(0xFF93C5FD)
val ClassicOnPrimaryDark = Color(0xFF0F172A)
val ClassicPrimaryContainerDark = Color(0xFF1E293B)
val ClassicSecondaryDark = Color(0xFF60A5FA)
val ClassicTertiaryDark = Color(0xFF38BDF8)
val ClassicBackgroundDark = Color(0xFF0F172A)
val ClassicSurfaceDark = Color(0xFF1E293B)
val ClassicSurfaceVariantDark = Color(0xFF334155)

// Theme 2: Ocean (Teal, Cyan, Deep Sea)
val OceanPrimaryLight = Color(0xFF0E7490)
val OceanOnPrimaryLight = Color(0xFFFFFFFF)
val OceanPrimaryContainerLight = Color(0xFFCFFAFE)
val OceanSecondaryLight = Color(0xFF06B6D4)
val OceanTertiaryLight = Color(0xFF0284C7)
val OceanBackgroundLight = Color(0xFFF0FDFA)
val OceanSurfaceLight = Color(0xFFFFFFFF)
val OceanSurfaceVariantLight = Color(0xFFCCFBF1)

val OceanPrimaryDark = Color(0xFF67E8F9)
val OceanOnPrimaryDark = Color(0xFF083344)
val OceanPrimaryContainerDark = Color(0xFF155E75)
val OceanSecondaryDark = Color(0xFF22D3EE)
val OceanTertiaryDark = Color(0xFF38BDF8)
val OceanBackgroundDark = Color(0xFF082F49)
val OceanSurfaceDark = Color(0xFF0C4A6E)
val OceanSurfaceVariantDark = Color(0xFF164E63)

// Theme 3: Emerald (Royal Emerald, Mint, Pine)
val EmeraldPrimaryLight = Color(0xFF047857)
val EmeraldOnPrimaryLight = Color(0xFFFFFFFF)
val EmeraldPrimaryContainerLight = Color(0xFFD1FAE5)
val EmeraldSecondaryLight = Color(0xFF10B981)
val EmeraldTertiaryLight = Color(0xFF059669)
val EmeraldBackgroundLight = Color(0xFFF0FDF4)
val EmeraldSurfaceLight = Color(0xFFFFFFFF)
val EmeraldSurfaceVariantLight = Color(0xFFDCFCE7)

val EmeraldPrimaryDark = Color(0xFF6EE7B7)
val EmeraldOnPrimaryDark = Color(0xFF022C22)
val EmeraldPrimaryContainerDark = Color(0xFF065F46)
val EmeraldSecondaryDark = Color(0xFF34D399)
val EmeraldTertiaryDark = Color(0xFFA7F3D0)
val EmeraldBackgroundDark = Color(0xFF022C22)
val EmeraldSurfaceDark = Color(0xFF064E3B)
val EmeraldSurfaceVariantDark = Color(0xFF065F46)

// Theme 4: Purple (Royal Violet, Lavender, Plum)
val PurplePrimaryLight = Color(0xFF6D28D9)
val PurpleOnPrimaryLight = Color(0xFFFFFFFF)
val PurplePrimaryContainerLight = Color(0xFFEDE9FE)
val PurpleSecondaryLight = Color(0xFF8B5CF6)
val PurpleTertiaryLight = Color(0xFFA855F7)
val PurpleBackgroundLight = Color(0xFFFAF5FF)
val PurpleSurfaceLight = Color(0xFFFFFFFF)
val PurpleSurfaceVariantLight = Color(0xFFF3E8FF)

val PurplePrimaryDark = Color(0xFFC4B5FD)
val PurpleOnPrimaryDark = Color(0xFF2E1065)
val PurplePrimaryContainerDark = Color(0xFF5B21B6)
val PurpleSecondaryDark = Color(0xFFA78BFA)
val PurpleTertiaryDark = Color(0xFFD8B4FE)
val PurpleBackgroundDark = Color(0xFF1E112A)
val PurpleSurfaceDark = Color(0xFF2E1065)
val PurpleSurfaceVariantDark = Color(0xFF4C1D95)

// Theme 5: Sunset (Amber, Coral, Terracotta)
val SunsetPrimaryLight = Color(0xFFB45309)
val SunsetOnPrimaryLight = Color(0xFFFFFFFF)
val SunsetPrimaryContainerLight = Color(0xFFFEF3C7)
val SunsetSecondaryLight = Color(0xFFF59E0B)
val SunsetTertiaryLight = Color(0xFFEA580C)
val SunsetBackgroundLight = Color(0xFFFFFBEB)
val SunsetSurfaceLight = Color(0xFFFFFFFF)
val SunsetSurfaceVariantLight = Color(0xFFFDE68A)

val SunsetPrimaryDark = Color(0xFFFCD34D)
val SunsetOnPrimaryDark = Color(0xFF451A03)
val SunsetPrimaryContainerDark = Color(0xFF78350F)
val SunsetSecondaryDark = Color(0xFFFBBF24)
val SunsetTertiaryDark = Color(0xFFFB923C)
val SunsetBackgroundDark = Color(0xFF1C1309)
val SunsetSurfaceDark = Color(0xFF2D1E0E)
val SunsetSurfaceVariantDark = Color(0xFF451A03)

// Theme 6: Ruby (Crimson / Deep Wine / Elegant Rose)
val RubyPrimaryLight = Color(0xFFBE123C)
val RubyOnPrimaryLight = Color(0xFFFFFFFF)
val RubyPrimaryContainerLight = Color(0xFFFFE4E6)
val RubySecondaryLight = Color(0xFFE11D48)
val RubyTertiaryLight = Color(0xFF9F1239)
val RubyBackgroundLight = Color(0xFFFFF1F2)
val RubySurfaceLight = Color(0xFFFFFFFF)
val RubySurfaceVariantLight = Color(0xFFFECDD3)

val RubyPrimaryDark = Color(0xFFFDA4AF)
val RubyOnPrimaryDark = Color(0xFF4C0519)
val RubyPrimaryContainerDark = Color(0xFF881337)
val RubySecondaryDark = Color(0xFFFB7185)
val RubyTertiaryDark = Color(0xFFF43F5E)
val RubyBackgroundDark = Color(0xFF1E0B11)
val RubySurfaceDark = Color(0xFF2A0F17)
val RubySurfaceVariantDark = Color(0xFF4C0519)

// Theme 7: Midnight Gold (Obsidian / Rich Gold / Luxury)
val MidnightGoldPrimaryLight = Color(0xFF854D0E)
val MidnightGoldOnPrimaryLight = Color(0xFFFFFFFF)
val MidnightGoldPrimaryContainerLight = Color(0xFFFEF08A)
val MidnightGoldSecondaryLight = Color(0xFFCA8A04)
val MidnightGoldTertiaryLight = Color(0xFFA16207)
val MidnightGoldBackgroundLight = Color(0xFFFAFAF9)
val MidnightGoldSurfaceLight = Color(0xFFFFFFFF)
val MidnightGoldSurfaceVariantLight = Color(0xFFF5F5F4)

val MidnightGoldPrimaryDark = Color(0xFFFACC15)
val MidnightGoldOnPrimaryDark = Color(0xFF422006)
val MidnightGoldPrimaryContainerDark = Color(0xFF713F12)
val MidnightGoldSecondaryDark = Color(0xFFEAB308)
val MidnightGoldTertiaryDark = Color(0xFFFDE047)
val MidnightGoldBackgroundDark = Color(0xFF141414)
val MidnightGoldSurfaceDark = Color(0xFF1F1F1F)
val MidnightGoldSurfaceVariantDark = Color(0xFF2E2E2E)

// Theme 8: Forest (Sage / Deep Olive / Forest Green)
val ForestPrimaryLight = Color(0xFF2D5A27)
val ForestOnPrimaryLight = Color(0xFFFFFFFF)
val ForestPrimaryContainerLight = Color(0xFFDCFCE7)
val ForestSecondaryLight = Color(0xFF4D7C0F)
val ForestTertiaryLight = Color(0xFF3F6212)
val ForestBackgroundLight = Color(0xFFF7FEE7)
val ForestSurfaceLight = Color(0xFFFFFFFF)
val ForestSurfaceVariantLight = Color(0xFFECFCCB)

val ForestPrimaryDark = Color(0xFF86EFAC)
val ForestOnPrimaryDark = Color(0xFF14532D)
val ForestPrimaryContainerDark = Color(0xFF166534)
val ForestSecondaryDark = Color(0xFFA3E635)
val ForestTertiaryDark = Color(0xFF4ADE80)
val ForestBackgroundDark = Color(0xFF0F1E11)
val ForestSurfaceDark = Color(0xFF182D1B)
val ForestSurfaceVariantDark = Color(0xFF1E3A22)
